
spring.datasource.url=${DB_URL:jdbc:postgresql://db.xgkmpsxijaulztaqfisl.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:qX9lS922mt7cH4Yx}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP — pool mínimo para ambiente de desenvolvimento
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5