spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/smartmenu}
spring.datasource.username=${DB_USERNAME:smartmenu}
spring.datasource.password=${DB_PASSWORD:smartmenu}
spring.datasource.driver-class-name=org.postgresql.Driver
postgresql://postgres:qX9lS922mt7cH4Yx@db.xgkmpsxijaulztaqfisl.supabase.co:5432/postgres
db.xgkmpsxijaulztaqfisl.supabase.co
5432
postgres
postgres